### ISSUE TITLE
META: Google Calendar Integration

### ISSUE THREAD

**Issue by acmahaja** [acmahaja/AstroAgenda#2]
- [ ] Google Calendar Integration
- [ ] Tasks can be viewed directly on the calendar interface.
- [ ] Synchronization ensures tasks and events are up-to-date.
