### ISSUE TITLE
META: Project Organization

### ISSUE THREAD

**Issue by acmahaja** [acmahaja/AstroAgenda#3]
- [ ] Project Organization
- [ ] Ability to create and manage multiple projects.
- [ ] Each project can have its own set of tasks and sublists.
- [ ] Projects provide a hierarchical structure for better task management.
