### ISSUE TITLE
META: Sublist Functionality

### ISSUE THREAD

**Issue by acmahaja** [acmahaja/AstroAgenda#4]
- [ ] Sublist Functionality
- [ ] Create sublists within projects for further categorization.
- [ ] Tasks can be assigned to specific sublists for detailed organization.
- [ ] Flexible management of tasks within sub-categories.
